INSERT INTO product VALUES (1000, 'f230fh0g3', 'Bamboo Watch', 'Product Description', 'INSTOCK', 'Accessories', 'bamboo-watch.jpg', 65, 24, 5);
INSERT INTO product VALUES (1001, 'nvklal433', 'Black Watch', 'Product Description', 'INSTOCK', 'Accessories', 'black-watch.jpg', 72, 61, 4);
INSERT INTO product VALUES (1002, 'zz21cz3c1', 'Blue Band', 'Product Description', 'LOWSTOCK', 'Fitness', 'blue-band.jpg', 79, 2, 3);
INSERT INTO product VALUES (1003, '244wgerg2', 'Blue T-Shirt', 'Product Description', 'INSTOCK', 'Clothing', 'blue-t-shirt.jpg', 29, 25, 5);
INSERT INTO product VALUES (1004, 'h456wer53', 'Bracelet', 'Product Description', 'INSTOCK', 'Accessories', 'bracelet.jpg', 15, 73, 4);
INSERT INTO product VALUES (1005, 'av2231fwg', 'Brown Purse', 'Product Description', 'OUTOFSTOCK', 'Accessories', 'brown-purse.jpg', 120, 0, 4);
INSERT INTO product VALUES (1006, 'bib36pfvm', 'Chakra Bracelet', 'Product Description', 'LOWSTOCK', 'Accessories', 'chakra-bracelet.jpg', 32, 5, 3);
INSERT INTO product VALUES (1007, 'mbvjkgip5', 'Galaxy Earrings', 'Product Description', 'INSTOCK', 'Accessories', 'galaxy-earrings.jpg', 34, 23, 5);
INSERT INTO product VALUES (1008, 'vbb124btr', 'Game Controller', 'Product Description', 'LOWSTOCK', 'Electronics', 'game-controller.jpg', 99, 2, 4);
INSERT INTO product VALUES (1009, 'cm230f032', 'Gaming Set', 'Product Description', 'INSTOCK', 'Electronics', 'gaming-set.jpg', 299, 63, 3);
INSERT INTO product VALUES (1010, 'plb34234v', 'Gold Phone Case', 'Product Description', 'OUTOFSTOCK', 'Accessories', 'gold-phone-case.jpg', 24, 0, 4);
INSERT INTO product VALUES (1011, '4920nnc2d', 'Green Earbuds', 'Product Description', 'INSTOCK', 'Electronics', 'green-earbuds.jpg', 89, 23, 4);
INSERT INTO product VALUES (1012, '250vm23cc', 'Green T-Shirt', 'Product Description', 'INSTOCK', 'Clothing', 'green-t-shirt.jpg', 49, 74, 5);
INSERT INTO product VALUES (1013, 'fldsmn31b', 'Grey T-Shirt', 'Product Description', 'OUTOFSTOCK', 'Clothing', 'grey-t-shirt.jpg', 48, 0, 3);
INSERT INTO product VALUES (1014, 'waas1x2as', 'Headphones', 'Product Description', 'LOWSTOCK', 'Electronics', 'headphones.jpg', 175, 8, 5);
INSERT INTO product VALUES (1015, 'vb34btbg5', 'Light Green T-Shirt', 'Product Description', 'INSTOCK', 'Clothing', 'light-green-t-shirt.jpg', 49, 34, 4);
INSERT INTO product VALUES (1016, 'k8l6j58jl', 'Lime Band', 'Product Description', 'INSTOCK', 'Fitness', 'lime-band.jpg', 79, 12, 3);
INSERT INTO product VALUES (1017, 'v435nn85n', 'Mini Speakers', 'Product Description', 'INSTOCK', 'Clothing', 'mini-speakers.jpg', 85, 42, 4);
INSERT INTO product VALUES (1018, '09zx9c0zc', 'Painted Phone Case', 'Product Description', 'INSTOCK', 'Accessories', 'painted-phone-case.jpg', 56, 41, 5);
INSERT INTO product VALUES (1019, 'mnb5mb2m5', 'Pink Band', 'Product Description', 'INSTOCK', 'Fitness', 'pink-band.jpg', 79, 63, 4);
INSERT INTO product VALUES (1020, 'r23fwf2w3', 'Pink Purse', 'Product Description', 'OUTOFSTOCK', 'Accessories', 'pink-purse.jpg', 110, 0, 4);
INSERT INTO product VALUES (1021, 'pxpzczo23', 'Purple Band', 'Product Description', 'LOWSTOCK', 'Fitness', 'purple-band.jpg', 79, 6, 3);
INSERT INTO product VALUES (1022, '2c42cb5cb', 'Purple Gemstone Necklace', 'Product Description', 'INSTOCK', 'Accessories', 'purple-gemstone-necklace.jpg', 45, 62, 4);
INSERT INTO product VALUES (1023, '5k43kkk23', 'Purple T-Shirt', 'Product Description', 'LOWSTOCK', 'Clothing', 'purple-t-shirt.jpg', 49, 2, 5);
INSERT INTO product VALUES (1024, 'lm2tny2k4', 'Shoes', 'Product Description', 'INSTOCK', 'Clothing', 'shoes.jpg', 64, 0, 4);
INSERT INTO product VALUES (1025, 'nbm5mv45n', 'Sneakers', 'Product Description', 'INSTOCK', 'Clothing', 'sneakers.jpg', 78, 52, 4);
INSERT INTO product VALUES (1026, 'zx23zc42c', 'Teal T-Shirt', 'Product Description', 'LOWSTOCK', 'Clothing', 'teal-t-shirt.jpg', 49, 3, 3);
INSERT INTO product VALUES (1027, 'acvx872gc', 'Yellow Earbuds', 'Product Description', 'INSTOCK', 'Electronics', 'yellow-earbuds.jpg', 89, 35, 3);
INSERT INTO product VALUES (1028, 'tx125ck42', 'Yoga Mat', 'Product Description', 'INSTOCK', 'Fitness', 'yoga-mat.jpg', 20, 15, 5);
INSERT INTO product VALUES (1029, 'gwuby345v', 'Yoga Set', 'Product Description', 'INSTOCK', 'Fitness', 'yoga-set.jpg', 20, 25, 8);